---
name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - name: Install deps
        run: yarn install
      - name: Set manifest version
        run: echo "RELEASE_VERSION=${REF##*/v}" >> $GITHUB_ENV
      - name: Build
        run: yarn build
      - name: Zip
        run: zip -r -j shopify-favicon-changer.zip ./dist/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            shopify-favicon-changer.zip
